The idea is to hvae a agent playing against another one and using the data (buffer ) generated to train the policy/value nn

In [61]:
import os
os.chdir('../src')
from game import Connect2
import random
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split

In [69]:
game = Connect2()

In [76]:
model = MLPRegressor(
    hidden_layer_sizes=(10,10),
    random_state=1, n_iter_no_change=10,
    max_iter=100, verbose=True,
    warm_start=True)
model.fit(X=pd.DataFrame(data=[[0,0,0,0]], columns=columns), y=pd.DataFrame(data=[[0]], columns=["target"]))

buffer_total = []
for j in range(10):
    df_buffer = pd.DataFrame()
    for i in range(10):
        game.reset()
        buffer = []
        while True:

            #random_action = random.choice(game._get_possible_actions(state=game.board))
            actions = game._get_possible_actions(state=game.board)
            lists=game._get_possible_next_states(state=game.board)

            model_action_max=np.argmax(model.predict(pd.DataFrame(lists, columns=columns)))
            #print(actions)
            #print(model_action_max)
            outcome = game.play_mcts(action=actions[model_action_max])#random_action)
            buffer.append((model_action_max, game.board, outcome, -game.player))
            buffer_total.append((model_action_max, game.board, outcome, -game.player))
            #game.render()
            #print(outcome)
            if outcome is not None:
                df_aux = from_buffer_to_df(buffer)
                df_buffer = pd.concat([df_buffer, df_aux]).copy()
                print(outcome)
                break


    df_train, columns = from_state_to_column(df_buffer.copy())
    df_train["target"] =df_buffer["reward"]


    X, y = df_train[columns], df_train["target"]
    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    random_state=1)
    model.fit(X=X_train, y=y_train)
    model.score(X_test, y_test)

/Users/pablocanadapereira/opt/anaconda3/envs/trading-bot/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

Iteration 1, loss = 0.03020677
Iteration 2, loss = 0.02834881
Iteration 3, loss = 0.02655438
Iteration 4, loss = 0.02482441
Iteration 5, loss = 0.02315967
Iteration 6, loss = 0.02156081
Iteration 7, loss = 0.02002832
Iteration 8, loss = 0.01856250
Iteration 9, loss = 0.01716352
Iteration 10, loss = 0.01583137
Iteration 11, loss = 0.01456586
Iteration 12, loss = 0.01336665
Iteration 13, loss = 0.01223321
Iteration 14, loss = 0.01116488
Iteration 15, loss = 0.01016081
Iteration 16, loss = 0.00922002
Iteration 17, loss = 0.00834138
Iteration 18, loss = 0.00752362
Iteration 19, loss = 0.00676532
Iteration 20, loss = 0.00606493
Iteration 21, loss = 0.00542076
Iteration 22, loss = 0.00483097
Iteration 23, loss = 0.00429360
Iteration 24, loss = 0.00380656
Iteration 25, loss = 0.00336765
Iteration 26, loss = 0.00297453
Iteration 27, loss = 0.00262481
Iteration 28, loss = 0.00231595
Iteration 29, loss = 0.00204540
Iteration 30, loss = 0.00181051
Iteration 31, loss = 0.00160861
Iteration 32, loss = 0.00143703
Iteration 33, loss = 0.00129306
Iteration 34, loss = 0.00117406
Iteration 35, loss = 0.00107741
Iteration 36, loss = 0.00100056
Iteration 37, loss = 0.00094104
Iteration 38, loss = 0.00089651
Iteration 39, loss = 0.00086473
Iteration 40, loss = 0.00084361
Iteration 41, loss = 0.00083120
Iteration 42, loss = 0.00082572
Iteration 43, loss = 0.00082557
Iteration 44, loss = 0.00082930
Iteration 45, loss = 0.00083567
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
0
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 46, loss = 0.18031012
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
1
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 47, loss = 0.17597802
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
2
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 48, loss = 0.17110343
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
3
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 49, loss = 0.16622375
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
4
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 50, loss = 0.16157674
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
5
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 51, loss = 0.15723585
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
6
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 52, loss = 0.15249063
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
7
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 53, loss = 0.14779808
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
8
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 54, loss = 0.14306548
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
9
0
1
1
1
2
1
3
1
4
1
5
1
6
1
7
1
8
1
9
1
Iteration 55, loss = 0.13771846
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

In [66]:
buffer_total

[(2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1),
 (2, [0, 0, 1, 0], None, 1),
 (0, [-1, 0, 1, 0], None, -1),
 (0, [-1, 1, 1, 0], 1, 1)]

In [52]:
actions = game._get_possible_actions(state=game.board)

In [53]:
    lists=game._get_possible_next_states(state=game.board)

In [54]:
lists

[[-1, 1, 1, -1]]

In [49]:
pd.DataFrame(data=[[0,0,0,0]], columns=columns)

   s_0  s_1  s_2  s_3
0    0    0    0    0

In [58]:
df_buffer

    action_taken          state  reward  player
0              2   [0, 0, 1, 0]     1.0       1
1              2  [1, 0, -1, 0]     0.0      -1
2              2  [-1, 1, 1, 0]     1.0       1
0              2   [0, 0, 1, 0]     1.0       1
1              2  [1, 0, -1, 0]     0.0      -1
..           ...            ...     ...     ...
1              2  [1, 0, -1, 0]     0.0      -1
2              2  [-1, 1, 1, 0]     1.0       1
0              2   [0, 0, 1, 0]     1.0       1
1              2  [1, 0, -1, 0]     0.0      -1
2              2  [-1, 1, 1, 0]     1.0       1

[300 rows x 4 columns]

In [51]:
model.predict(pd.DataFrame(data=[[0,-1,0,0]], columns=columns))

array([0.28842881])

In [55]:
game.reset()
actions=game._get_possible_actions(state=game.board)
print(actions)
lists=game._get_possible_next_states(state=game.board)
print(lists)

[0 1 2 3]
[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]

In [56]:
model.predict(pd.DataFrame(lists, columns=columns))

array([0.33938502, 0.40919533, 0.85232601, 0.15345781])

In [34]:
actions = game._get_possible_actions(state=game.board)
print(actions)

[0 1 2 3]

In [37]:
actions[2]

2

In [35]:
model.predict(pd.DataFrame(lists, columns=columns))

array([0.48167117, 0.61069045, 0.73385697, 0.39945526])

In [36]:
np.argmax(model.predict(pd.DataFrame(lists, columns=columns)))

2

In [23]:
np.argmax(model.predict(pd.DataFrame(lists, columns=columns)))

2

In [73]:
df_train["preds"] = model.predict(df_train[columns])

In [74]:
df_train

   s_0  s_1  s_2  s_3  target     preds
0    0    0    0    1     1.0  0.366677
1    1    0    0   -1     0.0  0.416638
2   -1    0    1    1     1.0  0.997187
0    0    0    1    0     1.0  0.779708
1    0    0   -1    1     0.0  0.066556
2    0    1    1   -1     1.0  1.123449
0    1    0    0    0     0.5  0.349925
1   -1    0    0    1     0.5  0.630562
2    1    0    1   -1     0.5  0.628422
3   -1    1   -1    1     0.5  0.281643
0    0    0    1    0     1.0  0.779708
1    1    0   -1    0     0.0  0.075396
2   -1    0    1    1     1.0  0.997187
0    1    0    0    0     0.5  0.349925
1   -1    1    0    0     0.5  0.763055
2    1   -1    1    0     0.5  0.352425
3   -1    1   -1    1     0.5  0.281643
0    0    0    0    1     0.5  0.366677
1    1    0    0   -1     0.5  0.416638
2   -1    1    0    1     0.5  0.746942
3    1   -1    1   -1     0.5  0.523335
0    0    1    0    0     0.5  0.527246
1    1   -1    0    0     0.5  0.317322
2   -1    1    0    1     0.5  0.746942
3    1   -1    1   -1     0.5  0.523335
0    0    0    1    0     1.0  0.779708
1    1    0   -1    0     0.0  0.075396
2   -1    1    1    0     1.0  1.190407
0    0    1    0    0     1.0  0.527246
1    0   -1    0    1     0.0  0.158706
2    0    1    1   -1     1.0  1.123449
0    0    1    0    0     1.0  0.527246
1    1   -1    0    0     0.0  0.317322
2   -1    1    1    0     1.0  1.190407

In [12]:
#buffer processing
import numpy as np
def invert_state(state):
    """From the perspective of player 1"""
    #if sum(np.array(state))!=0:
    state=[-x for x in state]
    return state

def from_buffer_to_df(buffer):
    buffer_df=pd.DataFrame(buffer, columns=["action_taken", "state", "reward", "player"])
    return handle_reward(buffer_df)

def from_state_to_column(df):
    assert "state" in df.columns
    df_out=pd.DataFrame()
    columns = [f"s_{x}" for x in range(len(df.state.iloc[0]))]
    df_out[columns] = pd.DataFrame(df.state.tolist(), index= df.index)
    
    return df_out, columns

def from_state_to_columns_model_pred(lists):


def handle_reward(df):
    df = df.copy()
    mask_not_null_reward = df.reward.notnull()
    mask_null_reward = df.reward.isnull()
    
    # invert state
    df.loc[(df.player==-1),"state"] = df[(df.player==-1)].state.apply(invert_state)
    
    if df[mask_not_null_reward].reward.values==0.5:
        df.loc[mask_null_reward, "reward"]=0.5
        
    elif df[mask_not_null_reward].reward.values!=0.5:
        reward = df[mask_not_null_reward].reward.values[0]
        #print(reward)
        player = df[mask_not_null_reward].player.values[0]
        #print(player)
        
        df.loc[(mask_null_reward) &
               (df.player==player)
               , "reward"]=reward
        
        df.loc[(mask_null_reward) &
               (df.player==-player)
               , "reward"]=1-reward
        
        # and invert state

        
    return df

In [61]:
buffer_df=pd.DataFrame(buffer, columns=["action_taken", "state", "reward", "player"])

In [50]:
df_train.state.iloc[0]

[0, 0, 1, 0]

In [51]:
columns = [f"s_{x}" for x in range(len(df_train.state.iloc[0]))]

In [52]:
columns

['s_0', 's_1', 's_2', 's_3']

In [56]:
from_state_to_column(df_train)

   s_0  s_1  s_2  s_3
0    0    0    1    0
1    1    0   -1    0
2   -1    1    1    0
0    0    0    1    0
1    0    1   -1    0
2    0   -1    1    1
0    0    1    0    0
1    0   -1    0    1
2    1    1    0   -1
0    0    0    0    1
1    1    0    0   -1
2   -1    1    0    1
3    1   -1    1   -1
0    0    0    0    1
1    1    0    0   -1
2   -1    1    0    1
3    1   -1    1   -1
0    0    0    0    1
1    1    0    0   -1
2   -1    1    0    1
3    1   -1    1   -1
0    0    0    0    1
1    0    1    0   -1
2    0   -1    1    1
0    1    0    0    0
1   -1    0    1    0
2    1    1   -1    0
0    0    0    0    1
1    0    0    1   -1
2    0    1   -1    1
3    1   -1    1   -1
0    0    1    0    0
1    1   -1    0    0
2   -1    1    1    0

In [58]:
buffer_df.iloc[17:21][(buffer_df.iloc[17:21].player==-1)].state.values[0]

[1, 0, -1, 0]

In [54]:
buffer_df.iloc[17:21][(buffer_df.iloc[17:21].player==-1)].state.apply(invert_state)

18     [1, 0, -1, 0]
20    [1, -1, -1, 1]
Name: state, dtype: object

In [63]:
handle_reward(buffer_df.iloc[17:21])

1.0
-1

    action_taken           state  reward  player
17             0    [1, 0, 0, 0]     0.0       1
18             2   [-1, 0, 1, 0]     1.0      -1
19             3   [1, 0, -1, 1]     0.0       1
20             1  [-1, 1, 1, -1]     1.0      -1

In [50]:
buffer_df_aux.loc[buffer_df_aux.reward==0.5]

   action_taken           state  reward  player
3             0  [-1, 1, -1, 1]     0.5      -1

In [ ]:

class Simulation:
    def __init__(self,):
        self.model =